kind: Deployment
apiVersion: apps/v1
metadata:
  name: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: registry.gitlab.com/opendatamtp/react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
